Replace TravisCI with Github Actions
SCE-Development/SCE-RPC pull request #71
Opened 2021-03-09 01:44 UTC by Christopher-Tom

2021-03-09 02:03 UTC, evanugarte approved these changes
[we played this](https://www.youtube.com/watch?v=kUsFWO08CO0) right as it passed

2021-03-09 02:03 UTC, evanugarte commented on .github/workflows/main.yml
> +#         python-version: [3.8]
```suggestion
```

2021-03-09 02:09 UTC, seemavora reviewed
remove comments

2021-03-09 02:40 UTC, seemavora reviewed
![image](https://user-images.githubusercontent.com/29296452/110410368-a08eb700-803d-11eb-8528-e43101da4db9.png)
I purposely made npm run test fail, but checks are still passing. See Issue #73

2021-03-09 05:29 UTC, seemavora commented on .github/workflows/main.yml
> +    runs-on: ubuntu-latest
I think Isita mentioned this in the Corev4 File, but is there a reason why it's just Ubuntu?

2021-03-09 05:29 UTC, seemavora commented on .github/workflows/main.yml
> +      - run: npm run lint
Re-tested with proper failure code, and it works. Love the error log much better than travis, looks more cleaner! 
![image](https://user-images.githubusercontent.com/29296452/110422957-17837a00-8055-11eb-8b86-378d641658c7.png)

2021-03-09 05:29 UTC, seemavora commented on .github/workflows/main.yml
> +      - run: npm run test
look at the comments above, but everything else looks good to me!

2021-03-09 05:30 UTC, seemavora approved these changes

2021-03-10 04:07 UTC, ThaiQ approved these changes

2021-03-11 02:11 UTC, charlotte-zhuang requested changes
It looks good. I think you need to change line 4, and we'd want to test a PR as well.

2021-03-11 02:11 UTC, charlotte-zhuang commented on .github/workflows/main.yml
> +        with:
It seems like we don't have a node version in `package.json`? Possibly omit to use whatever version of node is on the OS.

2021-03-11 02:11 UTC, charlotte-zhuang commented on .github/workflows/main.yml
> +  pull_request:
see [this doc](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions)

2021-03-11 03:22 UTC, seemavora commented
checked it again @Christopher-Tom and it works.

2021-03-16 01:45 UTC, charlotte-zhuang requested changes
`matrix.python-version` is undefined

2021-03-16 01:45 UTC, charlotte-zhuang commented on .github/workflows/main.yml
> +      - name: Use Node.js 14.x
```suggestion
      - name: Use Node.js
```

2021-03-16 01:45 UTC, charlotte-zhuang commented on .github/workflows/main.yml
> +      - name: Set up Python ${{ matrix.python-version }}
```suggestion
      - name: Set up Python
```

2021-03-16 01:45 UTC, charlotte-zhuang commented on .github/workflows/main.yml
> +        with:
```suggestion
```

2021-03-16 01:45 UTC, charlotte-zhuang commented on .github/workflows/main.yml
> +          python-version: ${{ matrix.python-version }}
```suggestion
```

2021-03-16 20:17 UTC, evanugarte approved these changes

2021-03-16 20:17 UTC, evanugarte commented on .github/workflows/main.yml
> +    runs-on: ${{ matrix.os }}
make it just ubuntu

2021-03-18 03:43 UTC, charlotte-zhuang reviewed
It looks good to me. See Evan's comments too. I wonder if this might have the same issue as Core-v4 where failed tests don't failed the check as well on Github.

2021-03-18 04:26 UTC, charlotte-zhuang approved these changes

2021-03-20 21:17 UTC, merged